### ISSUE TITLE
game center button not functioning

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#3]
Hello
The game center button is not functioning its always disabled and when I press on it it doesn't print on the debugging screen "click game center" can you please help
Thank you

**Comment by Evilcome** [comment]
@moh1122
Hi
You can find that when I create the game center button in `UISpriteComponent.swift` file, I set `gameCenterButton.isEnabled = false`, it always disabled.

Then, in the `GameViewController.swift` file, the current `GameViewController` class have `EasyGameCenterDelegate` protocol, in it's function `easyGameCenterAuthentified` I enable the game center button, this means after you success auth game center, the game center button will be enabled, and then when click you'll see the "click game center" on the debugging screen.

If you still got the game center button never enabled, it should because of you are not success login your game center. Manually open your Setting -> Game Center in your Device or Simulator, and check if you can success login. Looking more help at [Easy-Game-Center-Swift](https://github.com/DaRkD0G/Easy-Game-Center-Swift).

**Comment by moh1122** [comment]
tnks man I got it enabled ur hilarious. I changed  gameCenterButton.isEnabled = false to  gameCenterButton.isEnabled = true
but how can I add it to the game center games. Does it it need to be uploaded to apple so it shows in my games account.
I also have one more question:
Can I know how to make the sound mute as sound on/off in which .swift file
Thank you

**Comment by moh1122** [comment]
hi
I have successfully logged in to game center but its saying game not recognized by game center. is tht normal. is it because the game is not in the app-store?

**Comment by Evilcome** [comment]
Yes, game center use **sandbox** model when app during developing.

The sound question: 
Such as `Playground.swift`, I use the following code:

```
let sound = SKAction.playSoundFileNamed(Constant.background_sound, waitForCompletion: true)
runAction(SKAction.repeatActionForever(sound))
```

You can search `playSoundFileNamed` in whole project find other usage.
However, I do not found how to stop the sound or change the volume, can u help? :)

**Comment by moh1122** [comment]
thanks for your quick reply.
sure I can help, Volume goes from 0.0 to 1.0 (full volume). 
you can use backGroundMusic.volume = 0.5 so it would be lower. The user can lower the volume with the volume keys also.
You can use a slider also if you want?

**Comment by Evilcome** [comment]
thank you man.

it works with `AVAudioPlayer` framework, however, it seems can not set the volume for a `SKAction` based sound. I am not going to add `AVAudioPlayer` into the project now, it will cause the game performance or frames erratic. Any idea?

**Comment by moh1122** [comment]
That's true.
Cant we find a solution to put a mute button to stop all the sound depending on the users choice.

**Comment by Evilcome** [comment]
Yes, we can. but now, I'm going to focus on other game logic. And, I'll close this issue, feel free to create new issue or reopen this one. 😄
